const tarifa=0.95;
const API_BASE_URL="https://to-ligado-api.onrender.com";
let consumoTempoReal=[],labelsTempoReal=[],listaAlertasDiarios=[],dadosMensaisOriginais={labels:[],valores:[]},filtroAtivo=false;
const inputLimite=document.getElementById("limiteAlerta");
inputLimite.value=localStorage.getItem("limiteAlertaUsuario")||14080;
inputLimite.addEventListener("input",()=>localStorage.setItem("limiteAlertaUsuario",inputLimite.value));

const realtimeChart=new Chart(document.getElementById("realtimeChart"),{type:"line",data:{labels:labelsTempoReal,datasets:[{label:"Potência (W)",data:consumoTempoReal,borderColor:"#1769e0",backgroundColor:"rgba(23,105,224,.12)",tension:.35,fill:true,pointRadius:2,pointHoverRadius:6}]},options:{responsive:true,maintainAspectRatio:false,animation:false,scales:{y:{beginAtZero:true},x:{grid:{display:false}}}}});
const dailyChart=new Chart(document.getElementById("dailyChart"),{type:"bar",data:{labels:[],datasets:[{label:"Consumo (kWh)",data:[],backgroundColor:"#20a464",borderRadius:8}]},options:{responsive:true,maintainAspectRatio:false,scales:{y:{beginAtZero:true},x:{grid:{display:false}}},plugins:{tooltip:{callbacks:{footer:i=>{let k=i[0].parsed.y||0;return `🚨 Alertas: ${listaAlertasDiarios[i[0].dataIndex]||0}\n💰 Custo: R$ ${(k*tarifa).toFixed(2)}`}}}}}});
const monthlyChart=new Chart(document.getElementById("monthlyChart"),{type:"bar",data:{labels:[],datasets:[{label:"Consumo (kWh)",data:[],backgroundColor:"#e67e22",borderRadius:8}]},options:{responsive:true,maintainAspectRatio:false,scales:{y:{beginAtZero:true},x:{grid:{display:false}}},plugins:{tooltip:{callbacks:{footer:i=>`💰 Custo estimado: R$ ${((i[0].parsed.y||0)*tarifa).toFixed(2)}`}}}}});

function setStatus(ok){const p=document.getElementById("statusPill");p.classList.toggle("online",ok);p.classList.toggle("offline",!ok);document.getElementById("statusText").textContent=ok?"API online":"API indisponível"}
function verificarAlertaVisual(p){let l=parseFloat(inputLimite.value)||14080,c=document.getElementById("potencia").closest(".kpi-card"),s=document.getElementById("consumoStatus");if(p>l){c.style.borderTopColor="#e74c3c";s.textContent="⚠️ Alto consumo";s.style.color="#e74c3c"}else if(p>l*.8){c.style.borderTopColor="#f39c12";s.textContent="🟡 Atenção";s.style.color="#d68910"}else{c.style.borderTopColor="#1769e0";s.textContent="🟢 Consumo normal";s.style.color="#20a464"}}
async function atualizarDashboard(){
 try{let r=await fetch(`${API_BASE_URL}/dados_atuais?limite=${inputLimite.value||14080}`);if(!r.ok)throw Error(r.status);let d=await r.json();setStatus(true);document.getElementById("potencia").textContent=d.potencia+" W";document.getElementById("energiaDia").textContent=d.energiaDia+" kWh";document.getElementById("custo").textContent="R$ "+(d.energiaDia*tarifa).toFixed(2);document.getElementById("pico").textContent=d.picoDia+" W";document.getElementById("contadorAlertas").textContent=d.alertasHoje;verificarAlertaVisual(Number(d.potencia));if(consumoTempoReal.length>=20){consumoTempoReal.shift();labelsTempoReal.shift()}consumoTempoReal.push(Number(d.potencia));labelsTempoReal.push(new Date().toLocaleTimeString("pt-BR"));realtimeChart.update("none")}catch(e){setStatus(false);console.error(e)}
 try{let r=await fetch(`${API_BASE_URL}/historico_diario`);if(!r.ok)throw Error(r.status);let d=await r.json();dailyChart.data.labels=d.labels||[];dailyChart.data.datasets[0].data=d.valores||[];listaAlertasDiarios=d.alertas||[];dailyChart.update()}catch(e){console.error(e)}
}
async function carregarDadosMensais(){if(filtroAtivo)return;try{let r=await fetch(`${API_BASE_URL}/historico_mensal`);if(!r.ok)throw Error(r.status);let d=await r.json();dadosMensaisOriginais.labels=(d.labels||[]).slice(-6);dadosMensaisOriginais.valores=(d.valores||[]).slice(-6);monthlyChart.data.labels=[...dadosMensaisOriginais.labels];monthlyChart.data.datasets[0].data=[...dadosMensaisOriginais.valores];monthlyChart.update()}catch(e){console.error(e)}}
async function filtrarGraficoMensal(){let a=document.getElementById("anoFiltro").value,m=document.getElementById("mesFiltro").value;if(!a){alert("Selecione o ano.");return}try{let r=await fetch(`${API_BASE_URL}/filtrar_avancado?ano=${a}&mes=${m}`);if(!r.ok)throw Error(r.status);let d=await r.json();filtroAtivo=true;monthlyChart.data.labels=d.labels||[];monthlyChart.data.datasets[0].data=d.valores||[];monthlyChart.update()}catch(e){alert("Não foi possível carregar o filtro.")}}
function limparFiltroMensal(){filtroAtivo=false;document.getElementById("anoFiltro").value="2026";document.getElementById("mesFiltro").value="";monthlyChart.data.labels=[...dadosMensaisOriginais.labels];monthlyChart.data.datasets[0].data=[...dadosMensaisOriginais.valores];monthlyChart.update()}
document.getElementById("filterBtn").onclick=filtrarGraficoMensal;document.getElementById("clearBtn").onclick=limparFiltroMensal;
document.getElementById("refreshBtn").onclick=async e=>{e.currentTarget.textContent="↻ Atualizando...";await atualizarDashboard();await carregarDadosMensais();e.currentTarget.textContent="↻ Atualizar"};
if(localStorage.getItem("toLigadoTema")==="dark"){document.body.classList.add("dark");document.getElementById("themeBtn").textContent="☀️"}
document.getElementById("themeBtn").onclick=()=>{document.body.classList.toggle("dark");let d=document.body.classList.contains("dark");localStorage.setItem("toLigadoTema",d?"dark":"light");document.getElementById("themeBtn").textContent=d?"☀️":"🌙"};
setInterval(atualizarDashboard,2000);setInterval(carregarDadosMensais,10000);atualizarDashboard();carregarDadosMensais();